import "./globals.css";
import { Inter } from "next/font/google";
import DashboardWrapper from "./dashboardWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>
          {children}
          </DashboardWrapper></body>
    </html>
  );
}
